# Generated by Django 5.2.7 on 2025-12-07 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotional_value', models.PositiveSmallIntegerField(help_text='Emotional rating from 1 (negative) to 5 (positive)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('privacy_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Visibility of this emotion point', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this emotion point was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this emotion point was last updated')),
                ('location', models.ForeignKey(help_text='Location associated with this emotion', on_delete=django.db.models.deletion.CASCADE, related_name='emotion_points', to='map.location')),
                ('user', models.ForeignKey(help_text='User who created this emotion point', on_delete=django.db.models.deletion.CASCADE, related_name='emotion_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotion Point',
                'verbose_name_plural': 'Emotion Points',
                'db_table': 'emotions_emotion_point',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='emotions_user_created_idx'), models.Index(fields=['location', 'emotional_value'], name='emotions_loc_value_idx'), models.Index(fields=['privacy_status'], name='emotions_privacy_idx')],
                'unique_together': {('user', 'location')},
            },
        ),
    ]
