# Generated by Django 5.2.7 on 2026-01-03 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
        ('map', '0002_alter_location_options_alter_location_coordinates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotionpoint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Punkt emocji', 'verbose_name_plural': 'Punkty emocji'},
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Kiedy ten punkt emocji został utworzony'),
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='emotional_value',
            field=models.PositiveSmallIntegerField(help_text='Ocena emocjonalna od 1 (negatywna) do 5 (pozytywna)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='location',
            field=models.ForeignKey(help_text='Lokalizacja powiązana z tą emocją', on_delete=django.db.models.deletion.CASCADE, related_name='emotion_points', to='map.location'),
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny')], default='public', help_text='Widoczność tego punktu emocji', max_length=10),
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Kiedy ten punkt emocji był ostatnio aktualizowany'),
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='user',
            field=models.ForeignKey(help_text='Użytkownik, który utworzył ten punkt emocji', on_delete=django.db.models.deletion.CASCADE, related_name='emotion_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
