# Generated by Django 5.2.7 on 2026-01-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was created')),
                ('author', models.ForeignKey(help_text='User who wrote the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(help_text='The emotion point being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emotions.emotionpoint')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'emotions_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
