# Generated by Django 5.2.7 on 2026-01-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded image file', upload_to='emotion_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded')),
                ('point', models.ForeignKey(help_text='The emotion point this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='emotions.emotionpoint')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'emotions_photo',
                'ordering': ['-created_at'],
            },
        ),
    ]
