# Generated by Django 5.2.7 on 2026-01-03 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_alter_emotionpoint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Treść komentarza')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data utworzenia komentarza')),
                ('emotion_point', models.ForeignKey(help_text='Punkt emocji, którego dotyczy komentarz', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emotions.emotionpoint')),
                ('user', models.ForeignKey(help_text='Autor komentarza', on_delete=django.db.models.deletion.CASCADE, related_name='point_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'db_table': 'emotions_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
