# Generated by Django 6.0 on 2026-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionpoint',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny')], default='public', help_text="Status prywatności: 'public' (z imieniem i nazwiskiem, widoczne na profilu) lub 'private' (anonimowe, nie widoczne na profilu). Wszystkie emocje są widoczne na mapie.", max_length=10),
        ),
    ]
