# Generated by Django 6.0 on 2026-01-06 21:30

import django.db.models.deletion
import emotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionpoint',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny')], default='public', help_text="Status prywatności: 'public' (z imieniem i nazwiskiem, widoczne na profilu) lub 'private' (anonimowe, nie widoczne na profilu). Wszystkie emocje są widoczne na mapie.", max_length=10),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='emotion_photos/%Y/%m/%d/', validators=[emotions.models.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='emotions.emotionpoint')),
            ],
        ),
    ]
