# Generated by Django 6.0 on 2026-01-07 21:38

import django.db.models.deletion
import emotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_alter_emotionpoint_privacy_status'),
        ('map', '0002_alter_location_options_alter_location_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_photos/%Y/%m/%d/', validators=[emotions.models.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text='Lokalizacja, której dotyczy zdjęcie', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='map.location')),
            ],
        ),
    ]
