# Generated by Django 6.0.1 on 2026-01-09 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_alter_location_options_alter_location_coordinates_and_more'),
        ('emotions', '0005_photo'), # Dostosuj do ostatniej migracji, którą masz
    ]

    operations = [
        # 1. Dodajemy pole user do Photo
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Użytkownik, który dodał zdjęcie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        # 2. Przebudowa Comment: Usuwamy emotion_point, dodajemy location
        migrations.RemoveField(
            model_name='comment',
            name='emotion_point',
        ),
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(default=1, help_text='Lokalizacja, której dotyczy komentarz', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='map.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Autor komentarza', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]