# Generated by Django 6.0.1 on 2026-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0006_restructure_comments_and_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny')], default='public', help_text='Status prywatności komentarza', max_length=10),
        ),
    ]