# Generated by Django 6.0.1 on 2026-01-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0007_comment_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotion_point',
            field=models.ForeignKey(blank=True, help_text='Powiązana ocena (jeśli komentarz jest częścią opinii)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='emotions.emotionpoint'),
        ),
    ]