# Generated by Django 6.0.1 on 2026-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0008_link_comment_to_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny')], default='public', help_text='Status prywatności zdjęcia', max_length=10),
        ),
    ]