# Generated by Django 6.0 on 2026-04-27 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0009_photo_privacy'),
        ('map', '0002_alter_location_options_alter_location_coordinates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emotionpoint',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='emotionpoint',
            index=models.Index(fields=['location', 'user', '-created_at'], name='emotions_loc_user_created_idx'),
        ),
    ]
