# Generated by Django 6.0 on 2026-05-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0010_alter_emotionpoint_unique_together_and_more'),
        ('map', '0002_alter_location_options_alter_location_coordinates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam lub reklama'), ('hate_speech', 'Mowa nienawiści / Nękanie'), ('inappropriate', 'Nieodpowiednia treść'), ('fake_location', 'Fałszywa lokalizacja'), ('other', 'Inne')], max_length=20, verbose_name='Powód')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dodatkowy opis')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('resolved', 'Rozwiązane (Akceptacja)'), ('dismissed', 'Odrzucone (Brak naruszeń)')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpatrzenia')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='emotions.comment', verbose_name='Zgłoszony Komentarz')),
                ('emotion_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='emotions.emotionpoint', verbose_name='Zgłoszony Punkt Emocji')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='map.location', verbose_name='Zgłoszona Lokalizacja')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Rozpatrzone przez')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-created_at'],
            },
        ),
    ]
