# Generated by Django 6.0 on 2026-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0011_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment_label',
            field=models.CharField(blank=True, choices=[('negative', 'Negatywny'), ('neutral', 'Neutralny'), ('positive', 'Pozytywny')], help_text='Etykieta sentymentu: negative/neutral/positive', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Wynik sentymentu (1.0–5.0, ta sama skala co emotional_value)', null=True),
        ),
    ]
