# Generated by Django 6.0 on 2026-05-29 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0011_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Kiedy ten punkt emocji został utworzony'),
        ),
        migrations.AlterField(
            model_name='emotionpoint',
            name='emotional_value',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Ocena emocjonalna od 1 (negatywna) do 5 (pozytywna)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
