# Generated by Django 6.0 on 2026-05-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0012_alter_emotionpoint_created_at_and_more'),
        ('emotions', '0012_comment_sentiment_label_comment_sentiment_score'),
    ]

    operations = [
    ]
