# Generated by Django 5.2.7 on 2025-12-07 13:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location', max_length=200)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates (longitude, latitude)', srid=4326)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'map_location',
                'indexes': [models.Index(fields=['name'], name='location_name_idx')],
            },
        ),
    ]
