# Generated by Django 5.2.7 on 2026-01-03 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Lokalizacja', 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Współrzędne geograficzne (długość, szerokość)', srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Nazwa lokalizacji', max_length=200),
        ),
    ]
