# Generated by Django 6.0 on 2026-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_location_options_alter_location_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_name_idx',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
    ]
