# Generated by Django 6.0 on 2026-01-06 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='Użytkownik wysyłający zaproszenie', on_delete=django.db.models.deletion.CASCADE, related_name='created_friendships', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='Użytkownik otrzymujący zaproszenie', on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Znajomość',
                'verbose_name_plural': 'Znajomości',
                'ordering': ['-created_at'],
                'unique_together': {('creator', 'target')},
            },
        ),
    ]
