# Generated by Django 5.2.7 on 2026-01-03 09:59

import auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfuser',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AddField(
            model_name='cfuser',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cfuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Zdjęcie profilowe użytkownika', max_length=500, null=True, upload_to=auth.models.user_avatar_upload_path),
        ),
    ]
