# Generated by Django 6.0 on 2026-01-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_auth', '0002_alter_cfuser_options_cfuser_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('accepted', 'Zaakceptowane')], default='pending', help_text='Status relacji (pending/accepted)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data utworzenia relacji')),
                ('friend', models.ForeignKey(help_text='Użytkownik otrzymujący zaproszenie', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Użytkownik wysyłający zaproszenie', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Znajomość',
                'verbose_name_plural': 'Znajomości',
                'db_table': 'auth_friendship',
                'constraints': [models.UniqueConstraint(fields=('user', 'friend'), name='unique_friendship'), models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='users_cannot_be_friends_with_themselves')],
            },
        ),
    ]
